"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import MarqueeAnimation from "./components/MarqueeAnimation"
import HoverCard from "./components/HoverCard";
import CardSection from "./components/CardSection"
import HomeSection from "./components/HomeSection";
import Footer from "./components/Footer";
import FooterIcon from "./components/FooterIcon";

const inter = Inter({ subsets: ["latin"] });

 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
      <HomeSection/>
      <MarqueeAnimation/>
      <CardSection/>
      <Footer/>
      <FooterIcon/>
      
      {children}</body>
    </html>
  );
}
